-- Ancien seed de démonstration retiré : une installation neuve doit
-- démarrer vide, sans projet fictif (voir 002_seed.sql). Migration
-- conservée en no-op pour ne pas décaler la numérotation des suivantes.
